[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "dist/manjocarn"

[build.environment]
  # Variables publiques sécurisées - Ne mettez PAS votre token ici
  NODE_VERSION = "16"